name: tensorflow-3.5.1
dependencies:
- astroid=1.4.4=py35_0
- backports=1.0=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py35_0
- h5py=2.6.0=np111py35_1
- hdf5=1.8.16=0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jbig=2.1=0
- jpeg=8d=0
- lazy-object-proxy=1.2.1=py35_0
- libgfortran=3.0.0=1
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- logilab-common=1.0.2=py35_0
- matplotlib=1.5.1=np111py35_0
- mkl=11.3.3=0
- networkx=1.11=py35_0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pillow=3.2.0=py35_0
- pip=8.1.2=py35_0
- ptyprocess=0.5.1=py35_0
- pylint=1.5.4=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_3
- python=3.5.1=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- qt=4.8.7=3
- readline=6.2=2
- scikit-image=0.12.3=np111py35_0
- scikit-learn=0.17.1=np111py35_1
- scipy=0.17.1=np111py35_0
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- wrapt=1.10.6=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - keras==1.0.4
  - protobuf==3.0.0b2
  - pyyaml==3.11
  - tensorflow==0.9.0rc0
  - tflearn==0.2.1
  - theano==0.8.2
